require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const connectDatabase = require('./config/database');
const app = express();
const PORT = process.env.PORT || 3000;
connectDatabase().catch(err => { console.error(err); process.exit(1); });
app.use(cors());
app.use(express.json({ limit: '1mb' }));
app.use(express.static(path.join(__dirname, 'public')));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/store', require('./routes/store'));
app.get('/health', (req, res) => res.json({ ok: true, service: 'code-defender' }));
app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'public', 'index.html')));
app.listen(PORT, () => console.log('Code Defender server listening on port ' + PORT));
